version: "3"
services:
  app:
    container_name: zoomwolves_api
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27016:27017"

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo
    links:
      - mongo
