version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo
    links:
      - mongo
